id: PD2EAD4E3
initial_creation_type: input
source_metadata:
  title: Vajrāyudha
  language: en
  description: 'Texts by the master Vajrāyudha/Vajraśastra (rdo rje mtshon cha):'
  volume:
    463365abf22d41359cb8b79ef75ed73c:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      parent: Mañjuśrī
created_at: '2022-03-01T02:25:45.897078'
last_modified_at: '2022-03-01T02:25:45.897085'
